"""GTKWave adapter.

Upstream tool: GTKWave reading generated VCD files.
Install hint: install ``gtkwave`` on PATH; ``pyvcd`` is optional because this
adapter can emit the small VCD subset it needs by hand.
Supported capabilities: vcd_input, bit, bus, clock.
"""

from __future__ import annotations

from dataclasses import replace
from pathlib import Path
import shutil
import subprocess
import tempfile

from sva_toolkit.timing.render2.adapters._common import (
    base_layout,
    bbox_by_role,
    lane_display_name,
    samples_from_runs,
    supports_scene,
    text_primitives_from_tokens,
    visibility_report,
    with_bbox_by_role,
)
from sva_toolkit.timing.render2.primitives import Point
from sva_toolkit.timing.render2.result import RenderResult
from sva_toolkit.timing.render2.scene import LaneType, TimingScene
from sva_toolkit.timing.render2.spec import RenderSpec
from sva_toolkit.timing.visual import VisibilityClass


class GTKWaveAdapter:
    id = "gtkwave"
    capabilities = frozenset({"vcd_input", "bit", "bus", "clock"})

    def supports(self, scene: TimingScene, spec: RenderSpec) -> bool:
        return supports_scene(self.id, self.capabilities, scene, spec, dependency_available=shutil.which("gtkwave") is not None)

    def render(self, scene: TimingScene, spec: RenderSpec) -> RenderResult:
        if shutil.which("gtkwave") is None:
            raise RuntimeError("gtkwave is not installed; install GTKWave and ensure gtkwave is on PATH")
        if not self.supports(scene, spec):
            raise RuntimeError("gtkwave adapter does not support this scene/spec")

        png_bytes = _render_gtkwave_png(scene)
        layout = base_layout(scene, spec)
        text = _visibility_text(scene, spec)
        layout = with_bbox_by_role(layout, bbox_by_role(text))
        return RenderResult(
            svg_text=None,
            png_bytes=png_bytes,
            layout=layout,
            visibility=visibility_report(scene, text),
            render_spec=replace(spec, renderer_id=self.id),
            warnings=(),
        )


def dependency_status() -> str | None:
    return None if shutil.which("gtkwave") is not None else "missing_executable:gtkwave"


def _render_gtkwave_png(scene: TimingScene) -> bytes:
    with tempfile.TemporaryDirectory(prefix="sva-gtkwave-") as tmpdir:
        directory = Path(tmpdir)
        vcd = directory / "diagram.vcd"
        save = directory / "diagram.gtkw"
        script = directory / "capture.tcl"
        png = directory / "diagram.png"
        vcd.write_text(_build_vcd(scene), encoding="utf-8")
        save.write_text(_build_gtkw(scene, vcd), encoding="utf-8")
        script.write_text(_build_tcl(vcd, save, png), encoding="utf-8")
        subprocess.run(["gtkwave", "-S", str(script), str(vcd)], cwd=tmpdir, check=True, capture_output=True, timeout=45)
        if not png.exists():
            raise RuntimeError("gtkwave did not produce a PNG screenshot")
        return png.read_bytes()


def _build_vcd(scene: TimingScene) -> str:
    symbols = {lane.name: _symbol(index) for index, lane in enumerate(scene.lanes)}
    lines = [
        "$date generated by sva_toolkit $end",
        "$version sva_toolkit render2 gtkwave adapter $end",
        "$timescale 1ns $end",
        "$scope module timing $end",
    ]
    for lane in scene.lanes:
        width = _lane_width(lane)
        lines.append(f"$var wire {width} {symbols[lane.name]} {lane.name} $end")
    lines.extend(["$upscope $end", "$enddefinitions $end"])

    for tick in range(max(1, scene.ticks.total_ticks)):
        lines.append(f"#{tick}")
        for lane in scene.lanes:
            value = samples_from_runs(lane, scene.ticks.total_ticks)[tick]
            symbol = symbols[lane.name]
            if _lane_width(lane) == 1:
                lines.append(f"{_vcd_bit(value)}{symbol}")
            else:
                lines.append(f"b{_vcd_bus(value, _lane_width(lane))} {symbol}")
    return "\n".join(lines) + "\n"


def _build_gtkw(scene: TimingScene, vcd: Path) -> str:
    lines = ["[*]", f'[dumpfile] "{vcd}"', "@28"]
    lines.extend(lane.name for lane in scene.lanes)
    return "\n".join(lines) + "\n"


def _build_tcl(vcd: Path, save: Path, png: Path) -> str:
    return "\n".join(
        (
            f'gtkwave::loadFile "{vcd}"',
            f'gtkwave::/File/Read_Save_File "{save}"',
            "gtkwave::setZoomFactor -3",
            f'gtkwave::writeScreen "{png}"',
            "gtkwave::/File/Quit",
            "",
        )
    )


def _visibility_text(scene: TimingScene, spec: RenderSpec):
    tokens = []
    for lane_index, lane in enumerate(scene.lanes):
        y = spec.layout.margin.y + lane_index * spec.layout.lane_pitch + spec.layout.lane_height * 0.7
        tokens.append((lane_display_name(lane), "lane_label", VisibilityClass.VISIBLE_TEXT.value, Point(0.0, y)))
    return text_primitives_from_tokens(tokens, spec)


def _lane_width(lane) -> int:
    if lane.lane_type == LaneType.BUS and lane.width_bits:
        try:
            return max(1, int(lane.width_bits))
        except ValueError:
            return 1
    return 1


def _vcd_bit(value: str) -> str:
    text = str(value).lower()
    if text in {"1", "h", "high", "true"}:
        return "1"
    if text in {"0", "l", "low", "false"}:
        return "0"
    return "x"


def _vcd_bus(value: str, width: int) -> str:
    text = str(value).lower()
    if set(text) <= {"0", "1"}:
        return text.zfill(width)[-width:]
    return "x" * width


def _symbol(index: int) -> str:
    alphabet = tuple(chr(code) for code in range(33, 127))
    if index < len(alphabet):
        return alphabet[index]
    return f"s{index}"
